[build]
  command = "mkdocs build"
  publish = "site/"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.10"

[functions]
  directory = "netlify/functions"

[functions."app"]
  runtime = "python3.10"
